[build]
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  NETLIFY_USE_PNPM = "false"
  
  # Prisma
  PRISMA_GENERATE_FLAGS = "--generator client --schema=./prisma/schema.prisma"
  PRISMA_SKIP_POSTINSTALL = "true"
  
  # Next.js
  NEXT_TELEMETRY_DISABLED = "1"
  NEXT_SHARP_PATH = "./node_modules/sharp"

# Required for Next.js
[functions]
  external_node_modules = ["@prisma/client", "@prisma/engines", "prisma", "bcryptjs"]
  node_bundler = "esbuild"
  included_files = ["prisma/**"]

# Next.js plugin configuration
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Handle Next.js static files
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Security headers for all responses
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https:; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https:;"

# Handle API routes
[[redirects]]
  from = "/api/*"
  to = "/api/:splat"
  status = 200
  force = false

# Handle Next.js pages
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
