[build]
  command = "npm run build"
  publish = ".next"
  functions = ".next/server/functions"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  NETLIFY_USE_PNPM = "false"

# Required for Next.js
[functions]
  external_node_modules = ["@prisma/client", "@prisma/engines"]
  node_bundler = "esbuild"
  included_files = ["prisma/**"]

# Next.js plugin configuration
[[plugins]]
  package = "@netlify/plugin-nextjs"
  [plugins.inputs]
    functions_src = ".next/server/functions"
    functions_dist = "netlify/functions"

# Handle Next.js static files
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Security headers for all responses
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Handle API routes
[[redirects]]
  from = "/api/*"
  to = "/api/:splat"
  status = 200
  force = false

# Handle Next.js pages
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
