[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

# Handle Next.js static files and API routes
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Redirect all requests to Next.js
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# Handle Next.js static files
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Security headers for all responses
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https:; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https:;"

# Handle Next.js API routes
[[redirects]]
  from = "/api/*"
  to = "/api/:splat"
  status = 200
  force = true
